project:
  type: book

execute:
  freeze: auto

book:
  page-navigation: true
  title: "Template"
  site-url: "https://dst-lm166.github.io/Kampagne/" # replace ORGNAME and REPONAME
  repo-url: https://github.com/ORGNAME/Kampagne # replace ORGNAME and REPONAME
  repo-actions: [edit, issue]
  open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, style/style.scss]
      dark: [cosmo, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

bibliography: references.bib